export interface Template {
  id: string
  name: string
  description: string
  category: 'business' | 'creative' | 'tech' | 'minimal' | 'story'
  icon: string
  isPro?: boolean
  styles: TemplateStyles
}

export interface TemplateStyles {
  // Page
  backgroundColor: string
  maxWidth: string
  padding: string
  
  // Title
  titleFont: string
  titleSize: string
  titleWeight: string
  titleColor: string
  titleAlign?: string
  titleMarginBottom: string
  titleExtra?: string
  
  // Subtitle (h2)
  h2Font: string
  h2Size: string
  h2Weight: string
  h2Color: string
  h2BorderColor?: string
  h2MarginTop: string
  h2MarginBottom: string
  h2Extra?: string
  
  // H3
  h3Size: string
  h3Weight: string
  h3Color: string
  h3Extra?: string
  
  // Body text
  bodyFont: string
  bodySize: string
  bodyColor: string
  bodyLineHeight: string
  paragraphSpacing: string
  
  // Links
  linkColor: string
  linkHoverColor?: string
  
  // Blockquote
  blockquoteBorderColor: string
  blockquoteBg: string
  blockquoteColor: string
  blockquoteExtra?: string
  
  // Code
  codeBg: string
  codeColor: string
  codeBlockBg: string
  codeBlockColor: string
  codeBlockBorder?: string
  
  // Image
  imageRadius?: string
  imageShadow?: string
  
  // Table
  tableBorderColor: string
  tableHeaderBg: string
  tableHeaderColor: string
  tableStripeBg: string
  
  // Divider
  hrColor?: string
  dividerColor?: string
  
  // Strong / emphasis
  strongColor: string
  emColor: string
  
  // List
  listMarkerColor: string
}

// ============== 创意类主题 (Creative) ==============

export const playful: Template = {
  id: 'playful',
  name: '多彩活力',
  description: '高级多彩设计感，融合当代审美',
  category: 'creative',
  icon: '🌈',
  isPro: false,
  styles: {
    backgroundColor: '#fefdfb',
    maxWidth: '700px',
    padding: '56px 48px',
    titleFont: '"Georgia", "Noto Serif SC", serif',
    titleSize: '36px',
    titleWeight: '700',
    titleColor: '#1a1a1a',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '26px',
    h2Weight: '700',
    h2Color: '#0066cc',
    h2BorderColor: '#0066cc',
    h2MarginTop: '48px',
    h2MarginBottom: '20px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#1a4d99',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '17px',
    bodyColor: '#2c2c2c',
    bodyLineHeight: '1.9',
    paragraphSpacing: '20px',
    linkColor: '#0066cc',
    linkHoverColor: '#0052a3',
    blockquoteBorderColor: '#d4af37',
    blockquoteBg: '#fffbf0',
    blockquoteColor: '#4a4a4a',
    codeBg: '#f5f5f5',
    codeColor: '#c41e3a',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#2c2c2c',
    codeBlockBorder: '#d4af37',
    tableBorderColor: '#d4af37',
    tableHeaderBg: '#f5f5f5',
    tableHeaderColor: '#1a1a1a',
    tableStripeBg: '#fefdfb',
    hrColor: '#d4af37',
    dividerColor: '#d4af37',
    strongColor: '#1a1a1a',
    emColor: '#0066cc',
    listMarkerColor: '#d4af37',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const magazine: Template = {
  id: 'magazine',
  name: '杂志布局',
  description: '杂志风格布局，适合深度报道',
  category: 'creative',
  icon: '📰',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '740px',
    padding: '48px 40px',
    titleFont: '"Merriweather", Georgia, serif',
    titleSize: '36px',
    titleWeight: '900',
    titleColor: '#1a1a1a',
    titleAlign: 'left',
    titleMarginBottom: '12px',
    h2Font: '"Merriweather", Georgia, serif',
    h2Size: '26px',
    h2Weight: '700',
    h2Color: '#2c2c2c',
    h2BorderColor: '#1a1a1a',
    h2MarginTop: '44px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#3a3a3a',
    bodyFont: '"Georgia", serif',
    bodySize: '17px',
    bodyColor: '#333333',
    bodyLineHeight: '1.9',
    paragraphSpacing: '20px',
    linkColor: '#c41e3a',
    linkHoverColor: '#a01729',
    blockquoteBorderColor: '#c41e3a',
    blockquoteBg: '#fef2f2',
    blockquoteColor: '#4a4a4a',
    codeBg: '#f5f5f5',
    codeColor: '#c41e3a',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#333333',
    codeBlockBorder: '#e0e0e0',
    tableBorderColor: '#d6d6d6',
    tableHeaderBg: '#f5f5f5',
    tableHeaderColor: '#1a1a1a',
    tableStripeBg: '#fafafa',
    hrColor: '#d6d6d6',
    dividerColor: '#d6d6d6',
    strongColor: '#1a1a1a',
    emColor: '#c41e3a',
    listMarkerColor: '#c41e3a',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const artistic: Template = {
  id: 'artistic',
  name: '艺术创意',
  description: '装饰性创意元素，适合设计展示',
  category: 'creative',
  icon: '🎨',
  isPro: true,
  styles: {
    backgroundColor: '#f9f7f2',
    maxWidth: '680px',
    padding: '52px 44px',
    titleFont: '"Pacifico", cursive',
    titleSize: '34px',
    titleWeight: '400',
    titleColor: '#6b5b4e',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '"Quicksand", sans-serif',
    h2Size: '26px',
    h2Weight: '600',
    h2Color: '#8b7355',
    h2BorderColor: 'transparent',
    h2MarginTop: '40px',
    h2MarginBottom: '18px',
    h3Size: '21px',
    h3Weight: '600',
    h3Color: '#a68370',
    bodyFont: '"Quicksand", sans-serif',
    bodySize: '16px',
    bodyColor: '#3d3d3d',
    bodyLineHeight: '1.85',
    paragraphSpacing: '18px',
    linkColor: '#8b7355',
    linkHoverColor: '#6b5b4e',
    blockquoteBorderColor: '#c9a575',
    blockquoteBg: '#faf8f3',
    blockquoteColor: '#5a5a5a',
    codeBg: '#f0ebe5',
    codeColor: '#8b7355',
    codeBlockBg: '#f5f2ed',
    codeBlockColor: '#3d3d3d',
    codeBlockBorder: '#e0d5c7',
    tableBorderColor: '#e0d5c7',
    tableHeaderBg: '#f0ebe5',
    tableHeaderColor: '#3d3d3d',
    tableStripeBg: '#faf8f3',
    hrColor: '#e0d5c7',
    dividerColor: '#e0d5c7',
    strongColor: '#6b5b4e',
    emColor: '#8b7355',
    listMarkerColor: '#c9a575',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatElegant: Template = {
  id: 'wechat-elegant',
  name: '公众号·优雅',
  description: '经典公众号风格，优雅灵动',
  category: 'creative',
  icon: '✨',
  isPro: true,
  styles: {
    backgroundColor: '#fefbf7',
    maxWidth: '640px',
    padding: '52px 44px',
    titleFont: '"Noto Serif SC", Georgia, serif',
    titleSize: '34px',
    titleWeight: '700',
    titleColor: '#2c2c2c',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '"Noto Serif SC", Georgia, serif',
    h2Size: '26px',
    h2Weight: '600',
    h2Color: '#9b6b47',
    h2BorderColor: '#e8d5c4',
    h2MarginTop: '44px',
    h2MarginBottom: '18px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#a87555',
    bodyFont: '"Noto Sans SC", -apple-system, sans-serif',
    bodySize: '17px',
    bodyColor: '#3a3a3a',
    bodyLineHeight: '1.95',
    paragraphSpacing: '20px',
    linkColor: '#9b6b47',
    linkHoverColor: '#7a5636',
    blockquoteBorderColor: '#d4a89a',
    blockquoteBg: '#faf6f1',
    blockquoteColor: '#5a5a5a',
    codeBg: '#f5f0ea',
    codeColor: '#9b6b47',
    codeBlockBg: '#faf6f1',
    codeBlockColor: '#3a3a3a',
    codeBlockBorder: '#e8d5c4',
    tableBorderColor: '#e8d5c4',
    tableHeaderBg: '#f5f0ea',
    tableHeaderColor: '#2c2c2c',
    tableStripeBg: '#fefbf7',
    hrColor: '#e8d5c4',
    dividerColor: '#e8d5c4',
    strongColor: '#2c2c2c',
    emColor: '#9b6b47',
    listMarkerColor: '#d4a89a',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const medium: Template = {
  id: 'medium',
  name: 'Medium 长文',
  description: '内容平台风格，专注阅读',
  category: 'creative',
  icon: '📖',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '660px',
    padding: '60px 50px',
    titleFont: '"Tiempos Headline", Georgia, serif',
    titleSize: '38px',
    titleWeight: '700',
    titleColor: '#000000',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '"Tiempos Headline", Georgia, serif',
    h2Size: '26px',
    h2Weight: '700',
    h2Color: '#000000',
    h2BorderColor: 'transparent',
    h2MarginTop: '48px',
    h2MarginBottom: '20px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#333333',
    bodyFont: '"Charter", Georgia, serif',
    bodySize: '18px',
    bodyColor: '#36363636',
    bodyLineHeight: '2',
    paragraphSpacing: '24px',
    linkColor: '#36363636',
    linkHoverColor: '#000000',
    blockquoteBorderColor: '#36363636',
    blockquoteBg: 'transparent',
    blockquoteColor: '#757575',
    codeBg: '#f5f5f5',
    codeColor: '#d73a49',
    codeBlockBg: '#f6f8fa',
    codeBlockColor: '#36363636',
    codeBlockBorder: '#e1e4e8',
    tableBorderColor: '#e1e4e8',
    tableHeaderBg: '#f6f8fa',
    tableHeaderColor: '#000000',
    tableStripeBg: '#ffffff',
    hrColor: '#e1e4e8',
    dividerColor: '#e1e4e8',
    strongColor: '#000000',
    emColor: '#757575',
    listMarkerColor: '#36363636',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const hischeEditorial: Template = {
  id: 'hische-editorial',
  name: 'Hische·编辑部',
  description: '编辑部杂志风格 - 红色经典 + Bodoni 衬线',
  category: 'creative',
  icon: '📖',
  isPro: true,
  styles: {
    backgroundColor: '#fffef9',
    maxWidth: '700px',
    padding: '20px 20px 50px 20px',
    titleFont: '"Bodoni MT", "Didot", "Crimson Text", serif',
    titleSize: '32px',
    titleWeight: '400',
    titleColor: '#c9302c',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '"Bodoni MT", "Didot", serif',
    h2Size: '26px',
    h2Weight: '400',
    h2Color: '#2c2c2c',
    h2BorderColor: '#c9302c',
    h2MarginTop: '40px',
    h2MarginBottom: '18px',
    h3Size: '20px',
    h3Weight: '400',
    h3Color: '#2c2c2c',
    bodyFont: '"Crimson Text", Garamond, serif',
    bodySize: '17px',
    bodyColor: '#2c2c2c',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#c9302c',
    linkHoverColor: '#a32520',
    blockquoteBorderColor: '#c9302c',
    blockquoteBg: 'transparent',
    blockquoteColor: '#2c2c2c',
    codeBg: '#f9f9f9',
    codeColor: '#c9302c',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#2c2c2c',
    codeBlockBorder: '#e0e0e0',
    tableBorderColor: '#e0e0e0',
    tableHeaderBg: '#f9f9f9',
    tableHeaderColor: '#2c2c2c',
    tableStripeBg: '#ffffff',
    hrColor: '#c9302c',
    dividerColor: '#c9302c',
    strongColor: '#c9302c',
    emColor: '#2c2c2c',
    listMarkerColor: '#c9302c',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatElegantMinimal: Template = {
  id: 'wechat-elegant-minimal',
  name: '优雅简约',
  description: '宋体衬线 + 极简风格',
  category: 'creative',
  icon: '✨',
  isPro: false,
  styles: {
    backgroundColor: '#fff',
    maxWidth: '720px',
    padding: '40px 32px',
    titleFont: '"Songti SC", "SimSun", Georgia, serif',
    titleSize: '26px',
    titleWeight: '400',
    titleColor: '#1a1a1a',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '"Songti SC", Georgia, serif',
    h2Size: '22px',
    h2Weight: '400',
    h2Color: '#2c2c2c',
    h2BorderColor: 'transparent',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '18px',
    h3Weight: '400',
    h3Color: '#3a3a3a',
    bodyFont: '"Songti SC", "SimSun", Georgia, serif',
    bodySize: '17px',
    bodyColor: '#444',
    bodyLineHeight: '1.85',
    paragraphSpacing: '16px',
    linkColor: '#8b7355',
    linkHoverColor: '#6b5b4e',
    blockquoteBorderColor: '#ccc',
    blockquoteBg: 'transparent',
    blockquoteColor: '#666',
    codeBg: '#f5f5f5',
    codeColor: '#8b4513',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#444',
    codeBlockBorder: '#e0e0e0',
    tableBorderColor: '#e0e0e0',
    tableHeaderBg: '#f8f8f8',
    tableHeaderColor: '#555',
    tableStripeBg: '#fff',
    hrColor: '#e0e0e0',
    dividerColor: '#e0e0e0',
    strongColor: '#1a1a1a',
    emColor: '#666',
    listMarkerColor: '#8b7355',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

// ============== 技术类主题 (Tech) ==============

export const defaultTheme: Template = {
  id: 'default',
  name: 'GitHub Dark',
  description: '经典 GitHub 暗色主题，适合代码文档',
  category: 'tech',
  icon: '🌙',
  isPro: false,
  styles: {
    backgroundColor: '#252526',
    maxWidth: '900px',
    padding: '40px',
    titleFont: '"Noto Sans SC", -apple-system, sans-serif',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#ffffff',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '"Noto Sans SC", -apple-system, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#e2e8f0',
    h2BorderColor: '#3e3e42',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#cbd5e1',
    bodyFont: '"Noto Sans SC", -apple-system, sans-serif',
    bodySize: '16px',
    bodyColor: '#d4d4d4',
    bodyLineHeight: '1.8',
    paragraphSpacing: '8px',
    linkColor: '#4fc3f7',
    linkHoverColor: '#81d4fa',
    blockquoteBorderColor: '#4fc3f7',
    blockquoteBg: '#1e293b',
    blockquoteColor: '#94a3b8',
    codeBg: '#1e1e1e',
    codeColor: '#ce9178',
    codeBlockBg: '#1e1e1e',
    codeBlockColor: '#d4d4d4',
    codeBlockBorder: '#3e3e42',
    tableBorderColor: '#3e3e42',
    tableHeaderBg: '#1e1e1e',
    tableHeaderColor: '#ffffff',
    tableStripeBg: '#2d2d30',
    hrColor: '#3e3e42',
    dividerColor: '#3e3e42',
    strongColor: '#ffffff',
    emColor: '#4fc3f7',
    listMarkerColor: '#4fc3f7',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wired: Template = {
  id: 'wired',
  name: 'Wired 连线',
  description: '科技媒体风格，色彩鲜明',
  category: 'tech',
  icon: '⚡',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '740px',
    padding: '56px 48px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '40px',
    titleWeight: '900',
    titleColor: '#000000',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '28px',
    h2Weight: '800',
    h2Color: '#0066ff',
    h2BorderColor: '#0066ff',
    h2MarginTop: '44px',
    h2MarginBottom: '18px',
    h3Size: '20px',
    h3Weight: '700',
    h3Color: '#1a1a1a',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '17px',
    bodyColor: '#1a1a1a',
    bodyLineHeight: '1.85',
    paragraphSpacing: '18px',
    linkColor: '#0066ff',
    linkHoverColor: '#0052cc',
    blockquoteBorderColor: '#0066ff',
    blockquoteBg: '#f0f5ff',
    blockquoteColor: '#333333',
    codeBg: '#f5f5f5',
    codeColor: '#ff6600',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#1a1a1a',
    codeBlockBorder: '#0066ff',
    tableBorderColor: '#0066ff',
    tableHeaderBg: '#f0f5ff',
    tableHeaderColor: '#000000',
    tableStripeBg: '#ffffff',
    hrColor: '#0066ff',
    dividerColor: '#0066ff',
    strongColor: '#000000',
    emColor: '#0066ff',
    listMarkerColor: '#0066ff',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const anthropic: Template = {
  id: 'anthropic',
  name: 'Anthropic Claude',
  description: 'AI 时代风格，简洁现代',
  category: 'tech',
  icon: '🤖',
  isPro: true,
  styles: {
    backgroundColor: '#fafafa',
    maxWidth: '720px',
    padding: '56px 48px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '36px',
    titleWeight: '700',
    titleColor: '#000000',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#1a1a1a',
    h2BorderColor: '#e5e5e5',
    h2MarginTop: '44px',
    h2MarginBottom: '18px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#333333',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '16px',
    bodyColor: '#2c2c2c',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0066ff',
    linkHoverColor: '#0052cc',
    blockquoteBorderColor: '#d0d0d0',
    blockquoteBg: '#f5f5f5',
    blockquoteColor: '#555555',
    codeBg: '#f0f0f0',
    codeColor: '#d9453b',
    codeBlockBg: '#f5f5f5',
    codeBlockColor: '#2c2c2c',
    codeBlockBorder: '#e0e0e0',
    tableBorderColor: '#e0e0e0',
    tableHeaderBg: '#f5f5f5',
    tableHeaderColor: '#000000',
    tableStripeBg: '#fafafa',
    hrColor: '#e5e5e5',
    dividerColor: '#e5e5e5',
    strongColor: '#000000',
    emColor: '#555555',
    listMarkerColor: '#0066ff',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const code: Template = {
  id: 'code',
  name: '开发者',
  description: '开发者等宽字体，适合技术文档',
  category: 'tech',
  icon: '💻',
  isPro: true,
  styles: {
    backgroundColor: '#1e1e1e',
    maxWidth: '800px',
    padding: '40px 36px',
    titleFont: '"Fira Code", "Monaco", monospace',
    titleSize: '28px',
    titleWeight: '700',
    titleColor: '#4ec9b0',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '"Fira Code", "Monaco", monospace',
    h2Size: '22px',
    h2Weight: '600',
    h2Color: '#569cd6',
    h2BorderColor: '#569cd6',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#9cdcfe',
    bodyFont: '"Fira Code", "Monaco", monospace',
    bodySize: '15px',
    bodyColor: '#d4d4d4',
    bodyLineHeight: '1.7',
    paragraphSpacing: '16px',
    linkColor: '#4ec9b0',
    linkHoverColor: '#6dd9c0',
    blockquoteBorderColor: '#569cd6',
    blockquoteBg: '#2d2d30',
    blockquoteColor: '#9cdcfe',
    codeBg: '#2d2d30',
    codeColor: '#ce9178',
    codeBlockBg: '#1e1e1e',
    codeBlockColor: '#d4d4d4',
    codeBlockBorder: '#3e3e42',
    tableBorderColor: '#3e3e42',
    tableHeaderBg: '#2d2d30',
    tableHeaderColor: '#4ec9b0',
    tableStripeBg: '#252526',
    hrColor: '#3e3e42',
    dividerColor: '#3e3e42',
    strongColor: '#dcdcaa',
    emColor: '#c586c0',
    listMarkerColor: '#4ec9b0',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const terminal: Template = {
  id: 'terminal',
  name: '终端控制台',
  description: '终端控制台美学，适合命令行文档',
  category: 'tech',
  icon: '⌨️',
  isPro: true,
  styles: {
    backgroundColor: '#0c0c0c',
    maxWidth: '840px',
    padding: '32px 28px',
    titleFont: '"Courier New", monospace',
    titleSize: '26px',
    titleWeight: '700',
    titleColor: '#00ff00',
    titleAlign: 'left',
    titleMarginBottom: '20px',
    h2Font: '"Courier New", monospace',
    h2Size: '20px',
    h2Weight: '700',
    h2Color: '#00ff00',
    h2BorderColor: 'transparent',
    h2MarginTop: '32px',
    h2MarginBottom: '14px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#00cc00',
    bodyFont: '"Courier New", monospace',
    bodySize: '15px',
    bodyColor: '#c0c0c0',
    bodyLineHeight: '1.6',
    paragraphSpacing: '14px',
    linkColor: '#00ffff',
    linkHoverColor: '#00cccc',
    blockquoteBorderColor: '#00ff00',
    blockquoteBg: '#1a1a1a',
    blockquoteColor: '#a0a0a0',
    codeBg: '#1a1a1a',
    codeColor: '#ffff00',
    codeBlockBg: '#0c0c0c',
    codeBlockColor: '#c0c0c0',
    codeBlockBorder: '#333333',
    tableBorderColor: '#333333',
    tableHeaderBg: '#1a1a1a',
    tableHeaderColor: '#00ff00',
    tableStripeBg: '#0f0f0f',
    hrColor: '#333333',
    dividerColor: '#333333',
    strongColor: '#ffffff',
    emColor: '#ffff00',
    listMarkerColor: '#00ff00',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const cyberpunk: Template = {
  id: 'cyberpunk',
  name: '赛博朋克',
  description: '未来霓虹风格，适合科技前沿内容',
  category: 'tech',
  icon: '🌃',
  isPro: true,
  styles: {
    backgroundColor: '#0a0e27',
    maxWidth: '720px',
    padding: '44px 40px',
    titleFont: '"Orbitron", sans-serif',
    titleSize: '32px',
    titleWeight: '900',
    titleColor: '#ff00ff',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '"Orbitron", sans-serif',
    h2Size: '24px',
    h2Weight: '700',
    h2Color: '#00ffff',
    h2BorderColor: '#ff00ff',
    h2MarginTop: '40px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#00ff00',
    bodyFont: '"Rajdhani", sans-serif',
    bodySize: '16px',
    bodyColor: '#e0e0e0',
    bodyLineHeight: '1.75',
    paragraphSpacing: '16px',
    linkColor: '#ff00ff',
    linkHoverColor: '#ff66ff',
    blockquoteBorderColor: '#00ffff',
    blockquoteBg: '#1a1f3a',
    blockquoteColor: '#b0b0b0',
    codeBg: '#1a1f3a',
    codeColor: '#ff00ff',
    codeBlockBg: '#0d1117',
    codeBlockColor: '#e0e0e0',
    codeBlockBorder: '#ff00ff',
    tableBorderColor: '#00ffff',
    tableHeaderBg: '#1a1f3a',
    tableHeaderColor: '#ff00ff',
    tableStripeBg: '#0f1419',
    hrColor: '#00ffff',
    dividerColor: '#00ffff',
    strongColor: '#ff00ff',
    emColor: '#00ffff',
    listMarkerColor: '#00ff00',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const silicon: Template = {
  id: 'silicon',
  name: 'Silicon Valley',
  description: '科技感高级风格，适合技术内容',
  category: 'tech',
  icon: '💎',
  isPro: true,
  styles: {
    backgroundColor: '#fafbfc',
    maxWidth: '720px',
    padding: '56px 48px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#0a0e27',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#1a2332',
    h2BorderColor: '#e1e6ed',
    h2MarginTop: '44px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#3a4555',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '16px',
    bodyColor: '#3a4555',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0071e3',
    linkHoverColor: '#0077ed',
    blockquoteBorderColor: '#0071e3',
    blockquoteBg: '#f0f6ff',
    blockquoteColor: '#5a6b7a',
    codeBg: '#f5f7fa',
    codeColor: '#0071e3',
    codeBlockBg: '#f9fafb',
    codeBlockColor: '#3a4555',
    codeBlockBorder: '#e1e6ed',
    tableBorderColor: '#e1e6ed',
    tableHeaderBg: '#f9fafb',
    tableHeaderColor: '#0a0e27',
    tableStripeBg: '#fafbfc',
    hrColor: '#e1e6ed',
    dividerColor: '#e1e6ed',
    strongColor: '#0a0e27',
    emColor: '#5a6b7a',
    listMarkerColor: '#0071e3',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatTech: Template = {
  id: 'wechat-tech',
  name: '技术风格',
  description: '蓝绿色调 + 技术感',
  category: 'tech',
  icon: '💻',
  isPro: false,
  styles: {
    backgroundColor: '#fff',
    maxWidth: '740px',
    padding: '40px 32px',
    titleFont: '-apple-system, sans-serif',
    titleSize: '26px',
    titleWeight: '700',
    titleColor: '#1a1a1a',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '-apple-system, sans-serif',
    h2Size: '22px',
    h2Weight: '700',
    h2Color: '#1a1a1a',
    h2BorderColor: '#00a67d',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#2a2a2a',
    bodyFont: '-apple-system, sans-serif',
    bodySize: '16px',
    bodyColor: '#3a3a3a',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0066cc',
    linkHoverColor: '#0052a3',
    blockquoteBorderColor: '#2196f3',
    blockquoteBg: '#f5f9fc',
    blockquoteColor: '#555',
    codeBg: '#ffe6e6',
    codeColor: '#d63031',
    codeBlockBg: '#1e1e1e',
    codeBlockColor: '#f8fafc',
    codeBlockBorder: '#333333',
    tableBorderColor: '#0066cc',
    tableHeaderBg: '#0066cc',
    tableHeaderColor: '#fff',
    tableStripeBg: '#fff',
    hrColor: '#0066cc',
    dividerColor: '#0066cc',
    strongColor: '#1a1a1a',
    emColor: '#666',
    listMarkerColor: '#0066cc',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatClaude: Template = {
  id: 'wechat-claude',
  name: 'Claude AI',
  description: 'Anthropic Claude 风格 - 科技+温暖',
  category: 'tech',
  icon: '🤖',
  isPro: false,
  styles: {
    backgroundColor: '#faf9f7',
    maxWidth: '700px',
    padding: '40px 32px',
    titleFont: '-apple-system, BlinkMacSystemFont, sans-serif',
    titleSize: '32px',
    titleWeight: '600',
    titleColor: '#C15F3C',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, sans-serif',
    h2Size: '26px',
    h2Weight: '600',
    h2Color: '#C15F3C',
    h2BorderColor: '#C15F3C',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#C15F3C',
    bodyFont: '-apple-system, BlinkMacSystemFont, sans-serif',
    bodySize: '17px',
    bodyColor: '#2b2b2b',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#C15F3C',
    linkHoverColor: '#a04f2e',
    blockquoteBorderColor: '#C15F3C',
    blockquoteBg: 'rgba(193, 95, 60, 0.06)',
    blockquoteColor: '#2b2b2b',
    codeBg: 'rgba(193, 95, 60, 0.08)',
    codeColor: '#C15F3C',
    codeBlockBg: '#2b2b2b',
    codeBlockColor: '#f7f7f8',
    codeBlockBorder: '#3a3a3a',
    tableBorderColor: '#e0e0e0',
    tableHeaderBg: '#f5f5f5',
    tableHeaderColor: '#2b2b2b',
    tableStripeBg: '#faf9f7',
    hrColor: 'rgba(193, 95, 60, 0.3)',
    dividerColor: 'rgba(193, 95, 60, 0.3)',
    strongColor: '#C15F3C',
    emColor: '#5a5a5a',
    listMarkerColor: '#C15F3C',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

// ============== 极简类主题 (Minimal) ==============

export const githubLight: Template = {
  id: 'github-light',
  name: 'GitHub Light',
  description: '清爽的亮色主题，护眼舒适',
  category: 'minimal',
  icon: '☀️',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '900px',
    padding: '40px',
    titleFont: '"Noto Sans SC", -apple-system, sans-serif',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#1a1a1a',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '"Noto Sans SC", -apple-system, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#1a1a1a',
    h2BorderColor: '#e2e8f0',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#333333',
    bodyFont: '"Noto Sans SC", -apple-system, sans-serif',
    bodySize: '16px',
    bodyColor: '#333333',
    bodyLineHeight: '1.8',
    paragraphSpacing: '8px',
    linkColor: '#2563eb',
    linkHoverColor: '#1d4ed8',
    blockquoteBorderColor: '#2563eb',
    blockquoteBg: '#f0f7ff',
    blockquoteColor: '#4b5563',
    codeBg: '#f1f5f9',
    codeColor: '#e11d48',
    codeBlockBg: '#f8fafc',
    codeBlockColor: '#333333',
    codeBlockBorder: '#e2e8f0',
    tableBorderColor: '#e2e8f0',
    tableHeaderBg: '#f8fafc',
    tableHeaderColor: '#1a1a1a',
    tableStripeBg: '#fafbfc',
    hrColor: '#e2e8f0',
    dividerColor: '#e2e8f0',
    strongColor: '#1a1a1a',
    emColor: '#6b7280',
    listMarkerColor: '#2563eb',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const minimal: Template = {
  id: 'minimal',
  name: '极简现代',
  description: '极简设计，专注内容',
  category: 'minimal',
  icon: '✨',
  isPro: true,
  styles: {
    backgroundColor: '#fafafa',
    maxWidth: '680px',
    padding: '48px 32px',
    titleFont: '"Noto Sans SC", -apple-system, sans-serif',
    titleSize: '36px',
    titleWeight: '800',
    titleColor: '#111827',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '"Noto Sans SC", -apple-system, sans-serif',
    h2Size: '22px',
    h2Weight: '700',
    h2Color: '#111827',
    h2BorderColor: 'transparent',
    h2MarginTop: '40px',
    h2MarginBottom: '18px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#374151',
    bodyFont: '"Noto Sans SC", -apple-system, sans-serif',
    bodySize: '16px',
    bodyColor: '#374151',
    bodyLineHeight: '1.9',
    paragraphSpacing: '16px',
    linkColor: '#111827',
    linkHoverColor: '#374151',
    blockquoteBorderColor: '#111827',
    blockquoteBg: '#f9fafb',
    blockquoteColor: '#6b7280',
    codeBg: '#f3f4f6',
    codeColor: '#111827',
    codeBlockBg: '#f9fafb',
    codeBlockColor: '#374151',
    codeBlockBorder: '#e5e7eb',
    tableBorderColor: '#e5e7eb',
    tableHeaderBg: '#f9fafb',
    tableHeaderColor: '#111827',
    tableStripeBg: '#fafafa',
    hrColor: '#e5e7eb',
    dividerColor: '#e5e7eb',
    strongColor: '#111827',
    emColor: '#6b7280',
    listMarkerColor: '#111827',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const zen: Template = {
  id: 'zen',
  name: '禅意留白',
  description: '超极简留白设计，适合深度思考',
  category: 'minimal',
  icon: '🧘',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '600px',
    padding: '64px 48px',
    titleFont: '"Noto Serif SC", serif',
    titleSize: '28px',
    titleWeight: '400',
    titleColor: '#2c2c2c',
    titleAlign: 'left',
    titleMarginBottom: '40px',
    h2Font: '"Noto Serif SC", serif',
    h2Size: '22px',
    h2Weight: '400',
    h2Color: '#3a3a3a',
    h2BorderColor: 'transparent',
    h2MarginTop: '56px',
    h2MarginBottom: '24px',
    h3Size: '18px',
    h3Weight: '400',
    h3Color: '#4a4a4a',
    bodyFont: '"Noto Serif SC", serif',
    bodySize: '16px',
    bodyColor: '#4a4a4a',
    bodyLineHeight: '2.2',
    paragraphSpacing: '24px',
    linkColor: '#2c2c2c',
    linkHoverColor: '#1a1a1a',
    blockquoteBorderColor: '#d0d0d0',
    blockquoteBg: 'transparent',
    blockquoteColor: '#6a6a6a',
    codeBg: '#f9f9f9',
    codeColor: '#2c2c2c',
    codeBlockBg: '#fafafa',
    codeBlockColor: '#4a4a4a',
    codeBlockBorder: '#e8e8e8',
    tableBorderColor: '#e8e8e8',
    tableHeaderBg: '#fafafa',
    tableHeaderColor: '#2c2c2c',
    tableStripeBg: '#ffffff',
    hrColor: '#e8e8e8',
    dividerColor: '#e8e8e8',
    strongColor: '#2c2c2c',
    emColor: '#6a6a6a',
    listMarkerColor: '#d0d0d0',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const appleLight: Template = {
  id: 'apple-light',
  name: 'Apple Light',
  description: '纯净亮色，极简无衬线，高级感',
  category: 'minimal',
  icon: '✨',
  isPro: false,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '680px',
    padding: '56px 48px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#000000',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#1a1a1a',
    h2BorderColor: '#f5f5f5',
    h2MarginTop: '44px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#333333',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '16px',
    bodyColor: '#333333',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0071e3',
    linkHoverColor: '#0077ed',
    blockquoteBorderColor: '#d0d0d0',
    blockquoteBg: '#f9f9f9',
    blockquoteColor: '#666666',
    codeBg: '#f5f5f5',
    codeColor: '#d9453b',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#333333',
    codeBlockBorder: '#e8e8e8',
    tableBorderColor: '#e8e8e8',
    tableHeaderBg: '#f9f9f9',
    tableHeaderColor: '#000000',
    tableStripeBg: '#ffffff',
    hrColor: '#e8e8e8',
    dividerColor: '#e8e8e8',
    strongColor: '#000000',
    emColor: '#666666',
    listMarkerColor: '#0071e3',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const appleDark: Template = {
  id: 'apple-dark',
  name: 'Apple Dark',
  description: '深灰暗色，优雅极简，适合夜间阅读',
  category: 'minimal',
  icon: '🌙',
  isPro: true,
  styles: {
    backgroundColor: '#1d1d1f',
    maxWidth: '700px',
    padding: '56px 48px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#ffffff',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#f5f5f7',
    h2BorderColor: '#424245',
    h2MarginTop: '44px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#e5e5e7',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '16px',
    bodyColor: '#e5e5e7',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0a84ff',
    linkHoverColor: '#55b4ff',
    blockquoteBorderColor: '#424245',
    blockquoteBg: '#2a2a2d',
    blockquoteColor: '#a1a1a6',
    codeBg: '#2a2a2d',
    codeColor: '#ff9f0a',
    codeBlockBg: '#1d1d1f',
    codeBlockColor: '#e5e5e7',
    codeBlockBorder: '#424245',
    tableBorderColor: '#424245',
    tableHeaderBg: '#2a2a2d',
    tableHeaderColor: '#ffffff',
    tableStripeBg: '#1d1d1f',
    hrColor: '#424245',
    dividerColor: '#424245',
    strongColor: '#ffffff',
    emColor: '#a1a1a6',
    listMarkerColor: '#0a84ff',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const appleGray: Template = {
  id: 'apple-gray',
  name: 'Apple Gray',
  description: '中性灰系，SF Pro 风格，专业严谨',
  category: 'minimal',
  icon: '📱',
  isPro: true,
  styles: {
    backgroundColor: '#f5f5f7',
    maxWidth: '700px',
    padding: '56px 48px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#1d1d1f',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#424245',
    h2BorderColor: '#d5d5d7',
    h2MarginTop: '44px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#555555',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '16px',
    bodyColor: '#424245',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0071e3',
    linkHoverColor: '#0077ed',
    blockquoteBorderColor: '#d5d5d7',
    blockquoteBg: '#ffffff',
    blockquoteColor: '#666666',
    codeBg: '#ffffff',
    codeColor: '#d9453b',
    codeBlockBg: '#f9f9f9',
    codeBlockColor: '#424245',
    codeBlockBorder: '#e8e8e8',
    tableBorderColor: '#d5d5d7',
    tableHeaderBg: '#ffffff',
    tableHeaderColor: '#1d1d1f',
    tableStripeBg: '#f5f5f7',
    hrColor: '#d5d5d7',
    dividerColor: '#d5d5d7',
    strongColor: '#1d1d1f',
    emColor: '#666666',
    listMarkerColor: '#0071e3',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const minimalPro: Template = {
  id: 'minimal-pro',
  name: 'Minimal Pro',
  description: '极简升级版，严谨排版，高级感',
  category: 'minimal',
  icon: '◼️',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '660px',
    padding: '60px 50px',
    titleFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    titleSize: '30px',
    titleWeight: '800',
    titleColor: '#111827',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    h2Size: '22px',
    h2Weight: '700',
    h2Color: '#1f2937',
    h2BorderColor: 'transparent',
    h2MarginTop: '48px',
    h2MarginBottom: '20px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#374151',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '16px',
    bodyColor: '#374151',
    bodyLineHeight: '1.9',
    paragraphSpacing: '20px',
    linkColor: '#111827',
    linkHoverColor: '#1f2937',
    blockquoteBorderColor: '#d1d5db',
    blockquoteBg: 'transparent',
    blockquoteColor: '#6b7280',
    codeBg: '#f3f4f6',
    codeColor: '#111827',
    codeBlockBg: '#f9fafb',
    codeBlockColor: '#374151',
    codeBlockBorder: '#e5e7eb',
    tableBorderColor: '#e5e7eb',
    tableHeaderBg: '#f9fafb',
    tableHeaderColor: '#111827',
    tableStripeBg: '#ffffff',
    hrColor: '#e5e7eb',
    dividerColor: '#e5e7eb',
    strongColor: '#111827',
    emColor: '#6b7280',
    listMarkerColor: '#9ca3af',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const paper: Template = {
  id: 'paper',
  name: '纸质纹理',
  description: '纸质纹理效果，适合传统阅读',
  category: 'minimal',
  icon: '📄',
  isPro: true,
  styles: {
    backgroundColor: '#f4f1ea',
    maxWidth: '680px',
    padding: '48px 40px',
    titleFont: '"Crimson Text", Georgia, serif',
    titleSize: '32px',
    titleWeight: '600',
    titleColor: '#2c2416',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '"Crimson Text", Georgia, serif',
    h2Size: '24px',
    h2Weight: '600',
    h2Color: '#3d3426',
    h2BorderColor: 'transparent',
    h2MarginTop: '40px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#4e4436',
    bodyFont: '"Crimson Text", Georgia, serif',
    bodySize: '17px',
    bodyColor: '#3d3426',
    bodyLineHeight: '1.9',
    paragraphSpacing: '18px',
    linkColor: '#8b6914',
    linkHoverColor: '#6b5010',
    blockquoteBorderColor: '#c9b896',
    blockquoteBg: 'transparent',
    blockquoteColor: '#5e5446',
    codeBg: '#e8e3d6',
    codeColor: '#8b6914',
    codeBlockBg: '#ebe7dc',
    codeBlockColor: '#3d3426',
    codeBlockBorder: '#d4cdb8',
    tableBorderColor: '#d4cdb8',
    tableHeaderBg: '#e8e3d6',
    tableHeaderColor: '#2c2416',
    tableStripeBg: '#f9f7f2',
    hrColor: '#d4cdb8',
    dividerColor: '#d4cdb8',
    strongColor: '#2c2416',
    emColor: '#8b6914',
    listMarkerColor: '#c9b896',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatApple: Template = {
  id: 'wechat-apple',
  name: 'Apple 极简',
  description: 'Apple 设计哲学 - 极简克制',
  category: 'minimal',
  icon: '🌟',
  isPro: true,
  styles: {
    backgroundColor: '#fbfbfd',
    maxWidth: '640px',
    padding: '40px 32px',
    titleFont: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
    titleSize: '32px',
    titleWeight: '600',
    titleColor: '#1d1d1f',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
    h2Size: '26px',
    h2Weight: '600',
    h2Color: '#1d1d1f',
    h2BorderColor: '#d2d2d7',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#1d1d1f',
    bodyFont: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
    bodySize: '17px',
    bodyColor: '#86868b',
    bodyLineHeight: '1.65',
    paragraphSpacing: '16px',
    linkColor: '#06c',
    linkHoverColor: '#0077ed',
    blockquoteBorderColor: 'transparent',
    blockquoteBg: 'transparent',
    blockquoteColor: '#1d1d1f',
    codeBg: '#f5f5f7',
    codeColor: '#86868b',
    codeBlockBg: '#f5f5f7',
    codeBlockColor: '#86868b',
    codeBlockBorder: '#d2d2d7',
    tableBorderColor: '#d2d2d7',
    tableHeaderBg: '#f5f5f7',
    tableHeaderColor: '#1d1d1f',
    tableStripeBg: '#fbfbfd',
    hrColor: '#d2d2d7',
    dividerColor: '#d2d2d7',
    strongColor: '#1d1d1f',
    emColor: '#86868b',
    listMarkerColor: '#06c',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

// ============== 商务类主题 (Business) ==============

export const nytimes: Template = {
  id: 'nytimes',
  name: '纽约时报',
  description: '经典报业风格，严谨优雅',
  category: 'business',
  icon: '📰',
  isPro: true,
  styles: {
    backgroundColor: '#ffffff',
    maxWidth: '680px',
    padding: '56px 48px',
    titleFont: '"Georgia", "Noto Serif SC", serif',
    titleSize: '38px',
    titleWeight: '700',
    titleColor: '#000000',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '"Georgia", serif',
    h2Size: '24px',
    h2Weight: '700',
    h2Color: '#000000',
    h2BorderColor: '#cccccc',
    h2MarginTop: '44px',
    h2MarginBottom: '18px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#333333',
    bodyFont: '"Georgia", serif',
    bodySize: '18px',
    bodyColor: '#222222',
    bodyLineHeight: '1.95',
    paragraphSpacing: '18px',
    linkColor: '#0066cc',
    linkHoverColor: '#003399',
    blockquoteBorderColor: '#999999',
    blockquoteBg: 'transparent',
    blockquoteColor: '#666666',
    codeBg: '#f5f5f5',
    codeColor: '#333333',
    codeBlockBg: '#fafafa',
    codeBlockColor: '#222222',
    codeBlockBorder: '#cccccc',
    tableBorderColor: '#cccccc',
    tableHeaderBg: '#f5f5f5',
    tableHeaderColor: '#000000',
    tableStripeBg: '#ffffff',
    hrColor: '#cccccc',
    dividerColor: '#cccccc',
    strongColor: '#000000',
    emColor: '#666666',
    listMarkerColor: '#999999',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatNyt: Template = {
  id: 'wechat-nyt',
  name: '公众号·纽约时报',
  description: '纽约时报经典风格 - 黑白衬线',
  category: 'business',
  icon: '🗞️',
  isPro: true,
  styles: {
    backgroundColor: '#fff',
    maxWidth: '680px',
    padding: '40px 32px',
    titleFont: 'Georgia, "Times New Roman", serif',
    titleSize: '42px',
    titleWeight: '700',
    titleColor: '#000',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: 'Georgia, serif',
    h2Size: '32px',
    h2Weight: '700',
    h2Color: '#000',
    h2BorderColor: '#000',
    h2MarginTop: '36px',
    h2MarginBottom: '18px',
    h3Size: '24px',
    h3Weight: '600',
    h3Color: '#121212',
    bodyFont: 'Georgia, "Times New Roman", serif',
    bodySize: '18px',
    bodyColor: '#121212',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#326891',
    linkHoverColor: '#254c6b',
    blockquoteBorderColor: '#121212',
    blockquoteBg: '#f7f7f7',
    blockquoteColor: '#121212',
    codeBg: '#f0f0f0',
    codeColor: '#666',
    codeBlockBg: '#f7f7f7',
    codeBlockColor: '#121212',
    codeBlockBorder: '#ddd',
    tableBorderColor: '#ddd',
    tableHeaderBg: '#f7f7f7',
    tableHeaderColor: '#121212',
    tableStripeBg: '#fff',
    hrColor: '#ddd',
    dividerColor: '#ddd',
    strongColor: '#000',
    emColor: '#121212',
    listMarkerColor: '#326891',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatMedium: Template = {
  id: 'wechat-medium',
  name: '公众号·Medium',
  description: 'Medium 平台风格 - 优雅阅读',
  category: 'business',
  icon: '✍️',
  isPro: false,
  styles: {
    backgroundColor: '#fff',
    maxWidth: '680px',
    padding: '40px 32px',
    titleFont: 'Georgia, "Times New Roman", serif',
    titleSize: '28px',
    titleWeight: '700',
    titleColor: '#242424',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: 'Georgia, "Times New Roman", serif',
    h2Size: '24px',
    h2Weight: '700',
    h2Color: '#242424',
    h2BorderColor: '#e6e6e6',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#242424',
    bodyFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    bodySize: '17px',
    bodyColor: '#242424',
    bodyLineHeight: '1.7',
    paragraphSpacing: '16px',
    linkColor: '#242424',
    linkHoverColor: '#000000',
    blockquoteBorderColor: '#242424',
    blockquoteBg: 'transparent',
    blockquoteColor: '#242424',
    codeBg: '#f5f5f5',
    codeColor: '#d73a49',
    codeBlockBg: '#f7f7f7',
    codeBlockColor: '#242424',
    codeBlockBorder: '#e6e6e6',
    tableBorderColor: '#e6e6e6',
    tableHeaderBg: '#f7f7f7',
    tableHeaderColor: '#242424',
    tableStripeBg: '#fff',
    hrColor: '#e6e6e6',
    dividerColor: '#e6e6e6',
    strongColor: '#242424',
    emColor: '#242424',
    listMarkerColor: '#242424',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const wechatDeepread: Template = {
  id: 'wechat-deepread',
  name: '深度阅读',
  description: '深度长文 - 克制设计',
  category: 'business',
  icon: '📚',
  isPro: false,
  styles: {
    backgroundColor: '#fff',
    maxWidth: '680px',
    padding: '40px 32px',
    titleFont: '-apple-system, "SF Pro Text", sans-serif',
    titleSize: '26px',
    titleWeight: '700',
    titleColor: '#0a0a0a',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '-apple-system, sans-serif',
    h2Size: '22px',
    h2Weight: '700',
    h2Color: '#0a0a0a',
    h2BorderColor: '#e1e4e8',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#1a1a1a',
    bodyFont: '-apple-system, sans-serif',
    bodySize: '17px',
    bodyColor: '#1a1a1a',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#0066cc',
    linkHoverColor: '#0052a3',
    blockquoteBorderColor: '#0a0a0a',
    blockquoteBg: '#f8f9fa',
    blockquoteColor: '#1a1a1a',
    codeBg: '#f5f5f5',
    codeColor: '#d73a49',
    codeBlockBg: '#f6f8fa',
    codeBlockColor: '#1a1a1a',
    codeBlockBorder: '#e1e4e8',
    tableBorderColor: '#e1e4e8',
    tableHeaderBg: '#f6f8fa',
    tableHeaderColor: '#1a1a1a',
    tableStripeBg: '#fff',
    hrColor: '#e1e4e8',
    dividerColor: '#e1e4e8',
    strongColor: '#0a0a0a',
    emColor: '#2a2a2a',
    listMarkerColor: '#0066cc',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const guardian: Template = {
  id: 'guardian',
  name: 'Guardian 卫报',
  description: 'The Guardian 风格 - 蓝黄配色',
  category: 'business',
  icon: '🛡️',
  isPro: true,
  styles: {
    backgroundColor: '#fff',
    maxWidth: '700px',
    padding: '40px 32px',
    titleFont: '-apple-system, sans-serif',
    titleSize: '42px',
    titleWeight: '700',
    titleColor: '#052962',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '-apple-system, sans-serif',
    h2Size: '32px',
    h2Weight: '600',
    h2Color: '#052962',
    h2BorderColor: '#C70000',
    h2MarginTop: '36px',
    h2MarginBottom: '18px',
    h3Size: '24px',
    h3Weight: '600',
    h3Color: '#052962',
    bodyFont: '-apple-system, sans-serif',
    bodySize: '17px',
    bodyColor: '#121212',
    bodyLineHeight: '1.7',
    paragraphSpacing: '16px',
    linkColor: '#0084C6',
    linkHoverColor: '#006ba1',
    blockquoteBorderColor: '#C70000',
    blockquoteBg: '#FEC200',
    blockquoteColor: '#052962',
    codeBg: '#f6f6f6',
    codeColor: '#C70000',
    codeBlockBg: '#052962',
    codeBlockColor: '#ffffff',
    codeBlockBorder: '#052962',
    tableBorderColor: '#052962',
    tableHeaderBg: '#052962',
    tableHeaderColor: '#fff',
    tableStripeBg: '#fff',
    hrColor: '#052962',
    dividerColor: '#052962',
    strongColor: '#052962',
    emColor: '#333',
    listMarkerColor: '#C70000',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const warmDocs: Template = {
  id: 'warm-docs',
  name: '焦橙文档',
  description: '焦橙色 + 温暖文档风格',
  category: 'business',
  icon: '🧡',
  isPro: false,
  styles: {
    backgroundColor: '#FAFAF9',
    maxWidth: '700px',
    padding: '40px 32px',
    titleFont: '-apple-system, sans-serif',
    titleSize: '28px',
    titleWeight: '700',
    titleColor: '#1A1A1A',
    titleAlign: 'left',
    titleMarginBottom: '24px',
    h2Font: '-apple-system, sans-serif',
    h2Size: '22px',
    h2Weight: '700',
    h2Color: '#1A1A1A',
    h2BorderColor: '#C2410C',
    h2MarginTop: '36px',
    h2MarginBottom: '16px',
    h3Size: '18px',
    h3Weight: '600',
    h3Color: '#1A1A1A',
    bodyFont: '-apple-system, sans-serif',
    bodySize: '16px',
    bodyColor: '#1A1A1A',
    bodyLineHeight: '1.8',
    paragraphSpacing: '16px',
    linkColor: '#C2410C',
    linkHoverColor: '#9a3409',
    blockquoteBorderColor: '#C2410C',
    blockquoteBg: '#FFF7ED',
    blockquoteColor: '#1A1A1A',
    codeBg: '#F5F5F0',
    codeColor: '#C2410C',
    codeBlockBg: '#F5F5F0',
    codeBlockColor: '#1A1A1A',
    codeBlockBorder: '#E5E5E5',
    tableBorderColor: '#E5E5E5',
    tableHeaderBg: '#F5F5F0',
    tableHeaderColor: '#1A1A1A',
    tableStripeBg: '#FAFAF9',
    hrColor: '#E5E5E5',
    dividerColor: '#E5E5E5',
    strongColor: '#C2410C',
    emColor: '#6B6B6B',
    listMarkerColor: '#C2410C',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

// ============== 故事类主题 (Story) ==============

export const novel: Template = {
  id: 'novel',
  name: '小说阅读',
  description: '书籍阅读体验，适合长篇故事',
  category: 'story',
  icon: '📚',
  isPro: true,
  styles: {
    backgroundColor: '#faf8f3',
    maxWidth: '640px',
    padding: '56px 44px',
    titleFont: '"Libre Baskerville", Georgia, serif',
    titleSize: '30px',
    titleWeight: '700',
    titleColor: '#1a1a1a',
    titleAlign: 'left',
    titleMarginBottom: '32px',
    h2Font: '"Libre Baskerville", Georgia, serif',
    h2Size: '24px',
    h2Weight: '700',
    h2Color: '#2c2c2c',
    h2BorderColor: 'transparent',
    h2MarginTop: '48px',
    h2MarginBottom: '20px',
    h3Size: '20px',
    h3Weight: '600',
    h3Color: '#3a3a3a',
    bodyFont: '"Libre Baskerville", Georgia, serif',
    bodySize: '17px',
    bodyColor: '#2c2c2c',
    bodyLineHeight: '2',
    paragraphSpacing: '20px',
    linkColor: '#8b4513',
    linkHoverColor: '#6b3410',
    blockquoteBorderColor: '#d4a574',
    blockquoteBg: 'transparent',
    blockquoteColor: '#5a5a5a',
    codeBg: '#f0ebe3',
    codeColor: '#8b4513',
    codeBlockBg: '#f5f2ed',
    codeBlockColor: '#2c2c2c',
    codeBlockBorder: '#e0d8cc',
    tableBorderColor: '#e0d8cc',
    tableHeaderBg: '#f0ebe3',
    tableHeaderColor: '#1a1a1a',
    tableStripeBg: '#faf8f3',
    hrColor: '#e0d8cc',
    dividerColor: '#e0d8cc',
    strongColor: '#1a1a1a',
    emColor: '#8b4513',
    listMarkerColor: '#d4a574',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

export const journal: Template = {
  id: 'journal',
  name: '个人日记',
  description: '个人日记风格，适合随笔记录',
  category: 'story',
  icon: '📔',
  isPro: true,
  styles: {
    backgroundColor: '#f9f8f6',
    maxWidth: '620px',
    padding: '48px 40px',
    titleFont: '"Dancing Script", cursive',
    titleSize: '32px',
    titleWeight: '700',
    titleColor: '#4a5046',
    titleAlign: 'left',
    titleMarginBottom: '28px',
    h2Font: '"Indie Flower", cursive',
    h2Size: '24px',
    h2Weight: '400',
    h2Color: '#5a6456',
    h2BorderColor: 'transparent',
    h2MarginTop: '40px',
    h2MarginBottom: '18px',
    h3Size: '20px',
    h3Weight: '400',
    h3Color: '#6b7566',
    bodyFont: '"Patrick Hand", cursive',
    bodySize: '16px',
    bodyColor: '#3d3d3d',
    bodyLineHeight: '1.95',
    paragraphSpacing: '18px',
    linkColor: '#6b7355',
    linkHoverColor: '#5a6456',
    blockquoteBorderColor: '#95a7b8',
    blockquoteBg: '#f5f4f0',
    blockquoteColor: '#5a5a5a',
    codeBg: '#eef0ee',
    codeColor: '#6b7355',
    codeBlockBg: '#f5f4f0',
    codeBlockColor: '#3d3d3d',
    codeBlockBorder: '#d4dde5',
    tableBorderColor: '#d4dde5',
    tableHeaderBg: '#eef0ee',
    tableHeaderColor: '#4a5046',
    tableStripeBg: '#f9f8f6',
    hrColor: '#d4dde5',
    dividerColor: '#d4dde5',
    strongColor: '#4a5046',
    emColor: '#6b7355',
    listMarkerColor: '#95a7b8',
    imageRadius: '8px',
    imageShadow: '0 2px 12px rgba(0,0,0,0.08)',
  }
}

// ============== 导出所有主题 ==============

export const allTemplates: Template[] = [
  // Creative (7个)
  playful,
  magazine,
  artistic,
  wechatElegant,
  medium,
  hischeEditorial,
  wechatElegantMinimal,
  
  // Tech (9个)
  defaultTheme,
  wired,
  anthropic,
  code,
  terminal,
  cyberpunk,
  silicon,
  wechatTech,
  wechatClaude,
  
  // Minimal (9个)
  githubLight,
  minimal,
  zen,
  appleLight,
  appleDark,
  appleGray,
  minimalPro,
  paper,
  wechatApple,
  
  // Business (6个)
  nytimes,
  wechatNyt,
  wechatMedium,
  wechatDeepread,
  guardian,
  warmDocs,
  
  // Story (2个)
  novel,
  journal,
]

export const themesByCategory = {
  creative: allTemplates.filter(t => t.category === 'creative'),
  tech: allTemplates.filter(t => t.category === 'tech'),
  minimal: allTemplates.filter(t => t.category === 'minimal'),
  business: allTemplates.filter(t => t.category === 'business'),
  story: allTemplates.filter(t => t.category === 'story'),
}

export const freeThemes = allTemplates.filter(t => !t.isPro)
export const proThemes = allTemplates.filter(t => t.isPro)

export function getTemplateById(id: string): Template | undefined {
  return allTemplates.find(t => t.id === id)
}

export function getTemplatesByCategory(category: Template['category']): Template[] {
  return allTemplates.filter(t => t.category === category)
}
